import { BadRequestException, Inject, Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';

import {
  AuditClientService,
  type IAuditClient,
} from '@arbibot/nest-platform';
import { ExecutionPlanEntity } from '@arbibot/persistence';

import { BridgeAdapterFactoryService } from '../execution/bridge/bridge-adapter-factory.service';

import type {
  CreateMultiLegPlanDto,
  LegDescriptorDto,
} from './dto/create-multi-leg-plan.dto';

// ───────────────────────────────────────────────────────────────────────
// Types
// ───────────────────────────────────────────────────────────────────────

/** Playbook config generated by the builder, stored on ExecutionPlan. */
export interface MultiLegPlaybookConfig {
  /** Schema version for forward compat. */
  readonly schemaVersion: 1;
  /** Ordered leg descriptors with resolved defaults. */
  readonly legs: ReadonlyArray<ResolvedLegConfig>;
  /** Plan-level metadata. */
  readonly isCrossChain: boolean;
  /** Chain IDs involved (unique). */
  readonly chainIds: ReadonlyArray<number>;
}

/** Resolved leg config (after validation and default-filling). */
export interface ResolvedLegConfig {
  readonly legIndex: number;
  readonly legType: 'dex' | 'bridge';
  readonly chainId: number;
  readonly targetQuantity: number;
  // DEX-specific
  readonly venueKey?: string;
  /** Token to sell (DEX legs). Consumed by `extractSwapParams`/`extractSwapParamsV3`. */
  readonly tokenIn?: string;
  /** Token to buy (DEX legs). */
  readonly tokenOut?: string;
  /** Exact input amount in smallest token units, bigint string (DEX legs). */
  readonly amountIn?: string;
  /** Optional multi-hop path (DEX legs). Defaults to [tokenIn, tokenOut]. */
  readonly path?: readonly string[];
  /** Slippage tolerance in basis points (DEX legs). */
  readonly slippageBps?: number;
  /** Recipient wallet (DEX legs). */
  readonly recipient?: string;
  /** Deadline in seconds from now (DEX legs). */
  readonly deadlineSeconds?: number;
  /** Expected output amount, bigint string (V3 DEX legs). */
  readonly amountOutExpected?: string;
  /** Pool fee tier, uint24 (V3 DEX legs). */
  readonly fee?: number;
  /** V3 sqrtPriceLimitX96, bigint string (V3 DEX legs). */
  readonly sqrtPriceLimitX96?: string;
  // Bridge-specific
  readonly bridgeKey?: string;
  readonly destinationChainId?: number;
  readonly token?: string;
  readonly destinationToken?: string;
  readonly amount?: string;
  readonly recipientAddress?: string;
}

// ───────────────────────────────────────────────────────────────────────
// Service
// ───────────────────────────────────────────────────────────────────────

/**
 * Multi-leg plan builder — validates and builds cross-chain execution plans.
 *
 * Step: DEX-2-2-PLAN
 *
 * Responsibilities:
 * - Validate leg sequence: DEX → bridge → DEX pattern
 * - Validate bridge params (bridgeKey, chain pair, token, amount)
 * - Build `playbookConfig` JSON for the plan
 * - Create plan + store config
 *
 * Single-writer: execution-orchestrator owns ExecutionPlan.
 */
@Injectable()
export class MultiLegPlanBuilderService {
  private readonly logger = new Logger(MultiLegPlanBuilderService.name);

  constructor(
    private readonly dataSource: DataSource,
    @InjectRepository(ExecutionPlanEntity)
    private readonly plans: Repository<ExecutionPlanEntity>,
    @Inject(AuditClientService) private readonly audit: IAuditClient,
    private readonly bridgeAdapterFactory: BridgeAdapterFactoryService,
  ) {}

  /**
   * Build and persist a multi-leg cross-chain execution plan.
   *
   * Flow:
   * 1. Validate leg sequence structure
   * 2. Validate bridge leg params (bridge adapter exists, chain pair supported)
   * 3. Build playbookConfig
   * 4. Create plan in `planned` state
   * 5. Return plan with config
   */
  async buildMultiLegPlan(dto: CreateMultiLegPlanDto): Promise<{
    plan: ExecutionPlanEntity;
    config: MultiLegPlaybookConfig;
  }> {
    // 1. Validate structure
    this.validateLegSequence(dto.legs);

    // 2. Resolve defaults + validate bridge params
    const resolvedLegs = this.resolveAndValidateLegs(dto.legs);

    // 3. Build playbook config
    const chainIds = [...new Set(resolvedLegs.map((l) => l.chainId))];
    const isCrossChain = chainIds.length > 1;

    const config: MultiLegPlaybookConfig = {
      schemaVersion: 1,
      legs: resolvedLegs,
      isCrossChain,
      chainIds,
    };

    // 4. Create plan
    const plan = this.plans.create({
      correlationId: dto.correlationId ?? null,
      riskDecisionId: dto.riskDecisionId ?? null,
      routeKey: dto.routeKey?.trim() ?? null,
      state: 'planned',
      capitalReservationId: null,
      entityVersion: 1,
      playbookConfig: config as unknown as Record<string, unknown>,
    });

    const saved = await this.plans.save(plan);

    this.audit.record({
      idempotencyKey: `execution:CreateMultiLegPlan:${saved.id}`,
      correlationId: saved.correlationId ?? undefined,
      actor: 'execution-orchestrator',
      action: 'CreateMultiLegPlan',
      resourceType: 'ExecutionPlan',
      resourceId: saved.id,
      payload: {
        legCount: dto.legs.length,
        isCrossChain,
        chainIds,
        legTypes: resolvedLegs.map((l) => l.legType),
      },
    });

    this.logger.log(
      `Created multi-leg plan ${saved.id}: ${dto.legs.length} legs, ` +
      `crossChain=${isCrossChain}, chains=[${chainIds.join(', ')}]`,
    );

    return { plan: saved, config };
  }

  /**
   * Get the playbook config for a plan (typed).
   */
  static parsePlaybookConfig(
    raw: Record<string, unknown> | null | undefined,
  ): MultiLegPlaybookConfig | null {
    if (!raw || typeof raw !== 'object') return null;
    if (raw.schemaVersion !== 1) return null;
    if (!Array.isArray(raw.legs)) return null;
    return raw as unknown as MultiLegPlaybookConfig;
  }

  // ─────────────────────────────────────────────────────────────────────
  // Validation
  // ─────────────────────────────────────────────────────────────────────

  /**
   * Validate the overall leg sequence structure.
   *
   * Rules:
   * - Minimum 2 legs
   * - Maximum 8 legs
   * - Must start and end with DEX legs
   * - Bridge legs cannot be adjacent
   * - At most 2 bridge legs
   */
  private validateLegSequence(legs: LegDescriptorDto[]): void {
    if (legs.length < 2) {
      throw new BadRequestException(
        'Multi-leg plan must have at least 2 legs',
      );
    }

    if (legs.length > 8) {
      throw new BadRequestException(
        'Multi-leg plan must have at most 8 legs',
      );
    }

    // Must start with DEX
    if (!legs[0] || legs[0].legType !== 'dex') {
      throw new BadRequestException(
        'Multi-leg plan must start with a DEX leg (leg 0)',
      );
    }

    // Must end with DEX
    const lastLeg = legs[legs.length - 1];
    if (!lastLeg || lastLeg.legType !== 'dex') {
      throw new BadRequestException(
        `Multi-leg plan must end with a DEX leg (leg ${legs.length - 1})`,
      );
    }

    // No adjacent bridge legs
    let bridgeCount = 0;
    for (let i = 0; i < legs.length; i += 1) {
      const leg = legs[i]!;
      if (leg.legType === 'bridge') {
        bridgeCount += 1;
        // Adjacent bridge check
        if (i > 0 && legs[i - 1]!.legType === 'bridge') {
          throw new BadRequestException(
            `Adjacent bridge legs are not allowed (legs ${i - 1} and ${i})`,
          );
        }
      }
    }

    if (bridgeCount > 2) {
      throw new BadRequestException(
        'Multi-leg plan must have at most 2 bridge legs',
      );
    }
  }

  /**
   * Resolve defaults and validate per-leg params.
   */
  private resolveAndValidateLegs(
    legs: LegDescriptorDto[],
  ): ResolvedLegConfig[] {
    return legs.map((leg, index) => {
      const base: ResolvedLegConfig = {
        legIndex: index,
        legType: leg.legType,
        chainId: leg.chainId,
        targetQuantity: leg.targetQuantity ?? 10,
      };

      if (leg.legType === 'dex') {
        return {
          ...base,
          venueKey: leg.venueKey,
          // DEX swap params (D4-B-2c): carried through into playbookConfig.legs[]
          // so extractSwapParams / extractSwapParamsV3 resolve them on the live
          // path. Optional — when absent the live adapter throws a validation
          // error (no silent default for swap tokens/amounts).
          tokenIn: leg.tokenIn,
          tokenOut: leg.tokenOut,
          amountIn: leg.amountIn,
          path: leg.path,
          slippageBps: leg.slippageBps,
          recipient: leg.recipient,
          deadlineSeconds: leg.deadlineSeconds,
          amountOutExpected: leg.amountOutExpected,
          fee: leg.fee,
          sqrtPriceLimitX96: leg.sqrtPriceLimitX96,
        };
      }

      // Bridge leg validation
      return this.validateAndResolveBridgeLeg(leg, base, index);
    });
  }

  /**
   * Validate bridge leg parameters.
   */
  private validateAndResolveBridgeLeg(
    leg: LegDescriptorDto,
    base: ResolvedLegConfig,
    index: number,
  ): ResolvedLegConfig {
    if (!leg.bridgeKey) {
      throw new BadRequestException(
        `Bridge leg ${index} must specify bridgeKey`,
      );
    }

    if (!leg.destinationChainId) {
      throw new BadRequestException(
        `Bridge leg ${index} must specify destinationChainId`,
      );
    }

    if (!leg.token) {
      throw new BadRequestException(
        `Bridge leg ${index} must specify token`,
      );
    }

    if (!leg.destinationToken) {
      throw new BadRequestException(
        `Bridge leg ${index} must specify destinationToken`,
      );
    }

    if (!leg.amount) {
      throw new BadRequestException(
        `Bridge leg ${index} must specify amount`,
      );
    }

    // Validate amount is parseable as bigint
    try {
      BigInt(leg.amount);
    } catch {
      throw new BadRequestException(
        `Bridge leg ${index} amount must be a valid integer string`,
      );
    }

    // Validate bridge adapter exists
    if (!this.bridgeAdapterFactory.hasAdapter(leg.bridgeKey)) {
      throw new BadRequestException(
        `Bridge leg ${index}: unknown bridgeKey "${leg.bridgeKey}". ` +
        `Available: ${this.bridgeAdapterFactory.getRegisteredBridgeKeys().join(', ')}`,
      );
    }

    // Resolve adapter and validate chain pair
    const adapter = this.bridgeAdapterFactory.resolveAdapter(leg.bridgeKey);
    const pairSupported = adapter.supportedChains.some(
      ([src, dst]) =>
        src === leg.chainId && dst === leg.destinationChainId,
    );

    if (!pairSupported) {
      throw new BadRequestException(
        `Bridge leg ${index}: bridge "${leg.bridgeKey}" does not support ` +
        `${leg.chainId} → ${leg.destinationChainId}. ` +
        `Supported pairs: ${adapter.supportedChains.map(([s, d]) => `${s}→${d}`).join(', ')}`,
      );
    }

    return {
      ...base,
      bridgeKey: leg.bridgeKey,
      destinationChainId: leg.destinationChainId,
      token: leg.token,
      destinationToken: leg.destinationToken,
      amount: leg.amount,
      recipientAddress: leg.recipientAddress,
    };
  }
}